### ISSUE TITLE
Download not working anymore

### ISSUE THREAD

**Issue by jodur** [dunxd/HomeAssistantAddons#70]
I didn’t use addon for a while and always update to to latest version, without checking functionality.
Now i noticed that downloading isn’t working anymore?? (I tried different browsers)
Do i need to do additional settings to allow this? 
This was always working perfectly with my kobo reader.

Could this be related to: [https://github.com/mikespub-org/seblucas-cops/issues/113]([https://github.com/mikespub-org/seblucas-cops/issues/113) that is implemented in the new version?

**Comment by jodur** [comment]
Last update seems to resolve this problem for me

**Comment by dunxd** [comment]
I know mikespub had addressed some kobo specific things in recent updates to COPS so perhaps it was one of those chamges. Glad it is back working for you. 

I dont have a Kobo to test with so please do let me know if you notice anything breaking or have ideas for kobo specific improvements.
